### PR TITLE
orthonormalize subblocks when multiple species are present

### PR DESCRIPTION
**Pull request by arthur-lin1027**

### CODE REVIEW

**Comment by rosecers** [comment]
@arthur-lin1027 have you verified this works?

**Comment by arthur-lin1027** [comment]
> @arthur-lin1027 have you verified this works?

This works, but still need to confirm how to contract the two different species, and to see if it can learn the energies well

**Comment by rosecers** [comment]
Is this still active?

**Comment by arthur-lin1027** [comment]
I think this can be merged in. It doesn't affect the behavior of single species, and properly handles when there are multiple species.

**Review by rosecers — APPROVED** [review]

**Pull request merged**
