### PR TITLE
Merge documentation branch

### PR DESCRIPTION
**Pull request by ortengren**
Formatted all docstrings to align with NumPy standard.  Added configuration settings for Sphinx and ReadTheDocs, and built HTML files for API documentation.

### CODE REVIEW

**Comment by arthur-lin1027** [comment]
@rosecers @ortengren 

Should we have the documentation update every time we push to main through a github action? Something like https://stackoverflow.com/questions/57989790/using-github-actions-to-publish-documentation?rq=2

**Comment by rosecers** [comment]
Yes

**Comment by ortengren** [comment]
I can look into RTD webhooks and try to get that working.

**Review by arthur-lin1027 — APPROVED** [review]
I think the docs look great and seems to render great on the website.

**Review by arthur-lin1027 — COMMENTED** [review]
I think it looks great. @rosecers should we leave the github action for automatically updating the readthedocs for a later PR?

**Comment by rosecers** [comment]
> I think it looks great. @rosecers should we leave the github action for automatically updating the readthedocs for a later PR?

That should be fine, although it may be possible to setup outside of a PR

**Comment by rosecers** [comment]
It should be done through the readthedocs itself 

https://stackoverflow.com/questions/74950824/automatic-doc-build-on-readthedocs-org-on-every-new-commit

**Pull request merged**
